### ISSUE TITLE
Add support for specifying the license file in the config file

### ISSUE THREAD

**Issue by alex1989hu** [siderolabs/conform#195]
I would like to specify license header file. It is common to store a license file e.g. `LICENSE.txt` or `LICENSE` within the repository. The license file path option shall be mutually exclusive with the current option, `header`.

```yaml
  - type: license
    spec:
      skipPaths:
        - .git/
        - .build*/
      includeSuffixes:
        - .ext
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      headerPath:
        - LICENSE.txt
```
