### ISSUE TITLE
Configuration uses regex for conventional commit scope

### ISSUE THREAD

**Issue by syaghoubi00** [siderolabs/conform#266]
The [current scope parsing behavior](https://github.com/siderolabs/conform/blob/8078e02d1d2c5986bf89c3c1d46e7094520b0237/internal/policy/commit/check_conventional_commit.go#L99) returns true if the scope ***contains*** the regex pattern, not if the scope is an ***exact*** match.

`.conform.yaml`
```yaml
policies:
  - type: commit
    spec:
      conventional:
        types: ["type"]
        scopes: ["a"]
```

```sh
git commit --allow-empty -m "type(aa): some message"
POLICY         CHECK                      STATUS        MESSAGE
commit         Conventional Commit        PASS          Commit message is a valid conventional commit
license        File Header                PASS          All files have a valid license header
```

Using the exact match regex in the config;
`.conform.yaml`
```yaml
policies:
  - type: commit
    spec:
      conventional:
        types: ["type"]
        scopes: ["^a$"]
```
```sh
git commit --allow-empty -m "type(aa): some message"
POLICY         CHECK                      STATUS        MESSAGE                           
commit         Conventional Commit        FAILED        Invalid scope "aa": allowed scopes are [^a$]
license        File Header                PASS          All files have a valid license header
Error: 1 or more policy failed
```

---

The regex could be useful for defining more complex scope patterns, but it doesn't match what I would call expected behavior since the `types:` key doesn't use regex. Perhaps it would be better to add a `regex: bool` option to the config and do a non-regex scope match by default?
